### ISSUE TITLE
[Bug]: `Could not locate the bindings file.` after `pnpm i -r` command.

### ISSUE THREAD

**Issue by LWJerri** [mtcute/mtcute#16]
SQLite can't find the session file after `pnpm i -r` command.

## To Reproduce
1. Run `pnpm create @mtcute/bot my-awesome-bot`.
2. Wait until all dependencies are installed.
3. Delete the `node_modules` folder.
4. Install all packages with the `pnpm i -r` command.
5. Run `pnpm run run`.

## Expected behavior
An application must start as expected, without any errors.

## Logs
<details>
  <summary>`pnpm run run` output</summary>

LWJerri :: test/bug-reproduce » pnpm run run

> bug-reproduce@0.0.0 run /home/lwjerri/projects/SpotiGram/test/bug-reproduce
> tsc && dotenv node ./dist/index.js

Error: Could not locate the bindings file. Tried:
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/compiled/21.6.1/linux/x64/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/lib/binding/node-v120-linux-x64/better_sqlite3.node
    at bindings (/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.js:126:9)
    at new Database (/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/lib/database.js:48:64)
    at Database (/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/lib/database.js:11:10)
    at SqliteStorage.load (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+sqlite@0.6.0/node_modules/@mtcute/sqlite/esm/index.js:267:20)
    at NodeTelegramClient._loadStorage (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+core@0.6.0/node_modules/@mtcute/core/esm/base-client.js:75:34)
    at NodeTelegramClient.connect (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+core@0.6.0/node_modules/@mtcute/core/esm/base-client.js:103:20)
    at async NodeTelegramClient.call (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+core@0.6.0/node_modules/@mtcute/core/esm/base-client.js:158:13)
    at async start (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+client@0.6.0/node_modules/@mtcute/client/esm/methods/auth/start.js:30:20)
    at async NodeTelegramClient._start [as start] (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+client@0.6.0/node_modules/@mtcute/client/esm/client.js:1017:22) {
  tries: [
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/compiled/21.6.1/linux/x64/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/lib/binding/node-v120-linux-x64/better_sqlite3.node'
  ]
}
file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+sqlite@0.6.0/node_modules/@mtcute/sqlite/esm/index.js:315
        this._db.close();
                 ^

TypeError: Cannot read properties of undefined (reading 'close')
    at SqliteStorage._destroy (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+sqlite@0.6.0/node_modules/@mtcute/sqlite/esm/index.js:315:18)
    at file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+sqlite@0.6.0/node_modules/@mtcute/sqlite/esm/index.js:158:61
    at process.eventHandler (file:///home/lwjerri/projects/SpotiGram/test/bug-reproduce/node_modules/.pnpm/@mtcute+core@0.6.0/node_modules/@mtcute/core/esm/utils/platform/exit-hook.js:13:13)
    at process.emit (node:events:519:28)

Node.js v21.6.1
 ELIFECYCLE  Command failed with exit code 1.
</details>

## Environment
 - OS: `Windows 11 (WSL 2 with Ubuntu 22.04)`.
 - Runtime: `Node.js v21.6.1`.
 - mtcute version: `^0.6.0`.

**Additional context**
Some developers can use monorepository with this package, but it will not work, because we have this error.

**Comment by LWJerri** [comment]
Missed setup `pnpm-workspace.yaml` file.
