### ISSUE TITLE
[Bug]: Unknown object undefined when call `exportSession()`.

### ISSUE THREAD

**Issue by LWJerri** [mtcute/mtcute#17]
Hello, dear developer! When I call `exportSession()` I receive error `Error: Unknown object undefined`.

## To Reproduce
1. Log in to your account.
2. Call `exportSession()`.
3. See result.

## Expected behavior
Retrieve session string. 

## Logs
```txt
Error: Unknown object undefined
    at TlBinaryWriter.object (file:///home/lwjerri/projects/SpotiGram/node_modules/.pnpm/@mtcute+tl-runtime@0.7.0/node_modules/@mtcute/tl-runtime/esm/writer.js:243:19)
    at writeStringSession (file:///home/lwjerri/projects/SpotiGram/node_modules/.pnpm/@mtcute+core@0.7.0/node_modules/@mtcute/core/esm/utils/string-session.js:22:12)
    at BaseTelegramClient.exportSession (file:///home/lwjerri/projects/SpotiGram/node_modules/.pnpm/@mtcute+core@0.7.0/node_modules/@mtcute/core/esm/highlevel/base.js:168:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async saveSession (file:///home/lwjerri/projects/SpotiGram/dist/app.js:133:27)
    at async file:///home/lwjerri/projects/SpotiGram/dist/app.js:224:12
```

## Environment
 - OS: `Windows 11 (WSL 2 with Ubuntu 22.04)`.
 - Runtime: `Node.js v21.6.1`.
 - mtcute version: `^0.7.0`.

**Additional context**
I'm use `NodeTelegramClient` client instance from `@mtcute/node` package.

**Comment by LWJerri** [comment]
:shipit:

**Comment by LWJerri** [comment]
Hi, @teidesu (again). Problem is still exists after upgrading package to v^0.7.1 ;(

![image](https://github.com/mtcute/mtcute/assets/50290430/8d4936e3-420f-48d7-bf5b-d2ef352f0b06)

**Comment by teidesu** [comment]
bruh im retarded

**Comment by LWJerri** [comment]
un:shipit:
