### ISSUE TITLE
readHistory: type assertion

### ISSUE THREAD

**Issue by vanodevium** [mtcute/mtcute#84]
My is dead simple:

```js
await tg.readHistory(message.chat);
```

But in the console more and more messages like:

```
| MtTypeAssertionError: Type assertion error at channels.readHistory: expected true, but got false
|     at assertTrue (file:///app/node_modules/@mtcute/core/utils/type-assertions.js:27:11)
|     at readHistory (file:///app/node_modules/@mtcute/core/highlevel/methods/messages/read-history.js:27:5)
|     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|     at async Object.newMessageHandler [as callback] (file:///app/handlers/client/new-messages.js:26:5)
|     at async Dispatcher._dispatchUpdateNowImpl (file:///app/node_modules/@mtcute/dispatcher/dispatcher.js:286:26) {
|   context: 'channels.readHistory',
|   expected: 'true',
|   actual: 'false'
| }
```

It shows this warning in docker alpine container, macOS, anywhere.

Please give me advice how I can fix it.

**Comment by teidesu** [comment]
does the history actually get read?

**Comment by vanodevium** [comment]
Looks like yes, every time actually read. But with warning.
